version: "3.8"

services:
  api:
    build:
      dockerfile: ./.docker/api.dockerfile
    ports:
      - "8080:8080"
      - "5432:5432"
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecret
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    volumes:
      - ./api:/app
      - pgdata:/var/lib/postgresql/16/main
    command: >
      sh -c "cd /app &&
             service postgresql start &&
             chmod +x ./mvnw &&
             ./mvnw clean install &&
             ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  frontend:
    build:
      dockerfile: ./.docker/frontend.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    command: >
      sh -c "cd /app &&
             npm install &&
             ng serve --host 0.0.0.0 --poll 1"
volumes:
  pgdata:
