name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run tests
        run: |
          cd api
          mvn test

  build-and-deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t api-image -f .docker/api.dockerfile .
          docker save api-image > api-image.tar
       - name: Build Frontend Docker image
        run: |
          docker build -t frontend-image -f .docker/frontend.dockerfile .
          # Extraire les fichiers de build du conteneur
          docker create --name frontend-container frontend-image
          mkdir -p frontend-dist
          docker cp frontend-container:/app/dist/. frontend-dist/
          docker rm frontend-container
          tar -czf frontend-dist.tar.gz -C frontend-dist .

      - name: Transfer Frontend build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "frontend-dist.tar.gz"
          target: "/tmp"
      - name: Transfer Docker image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "api-image.tar"
          target: "/tmp"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker load < /tmp/api-image.tar
            docker stop api-container || true
            docker rm api-container || true
            docker run -d --name api-container -p 8080:8080 -p 5432:5432 api-image
            rm /tmp/api-image.tar

            # Déployer le frontend
            mkdir -p ${{ secrets.FRONT_PATH }}
            rm -rf ${{ secrets.FRONT_PATH }}/*
            tar -xzf /tmp/frontend-dist.tar.gz -C ${{ secrets.FRONT_PATH }}
            rm /tmp/frontend-dist.tar.gz